/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.dabad.vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import org.dabad.modelo.Libro;
import org.dabad.controlador.ControlDeLibro;

/**
 *
 * @author informatica
 */
class PanelDeImagen extends JPanel{
    private Image imagen;
    public PanelDeImagen(Image imagen){
        this.imagen = imagen;
    }
    @Override
    protected void paintComponent(Graphics grafica){
        super.paintComponent(grafica);
        grafica.drawImage(imagen, 0, 0, 400, 300, this);
    }
}
        

public class VentanaLibreria extends javax.swing.JFrame {

    private Image imagenDelPanel;
    /**
     * Creates new form VentanaLibreria
     */
    public VentanaLibreria() {
        String direccionImagen = "/org/dabad/recursos/MicrosoftTeams-image.png";
        cargarImagenDelPanel(this.getClass().getResource(direccionImagen));
        initComponents();
    }

    private void cargarImagenDelPanel(URL nombreImagen){
        try{
            imagenDelPanel = ImageIO.read(nombreImagen);
        }catch(IOException error){
           error.printStackTrace(); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentanaLibreria = new PanelDeImagen(imagenDelPanel);
        lblIdLibro = new javax.swing.JLabel();
        lblAutorLibro = new javax.swing.JLabel();
        lblNombreLibro = new javax.swing.JLabel();
        lblEditorialLibro = new javax.swing.JLabel();
        lblEdicionLibro = new javax.swing.JLabel();
        txtIdLibro = new javax.swing.JTextField();
        txtAutorLibro = new javax.swing.JTextField();
        txtNombreLibro = new javax.swing.JTextField();
        txtEditorialLibro = new javax.swing.JTextField();
        txtEdicionLibro = new javax.swing.JTextField();
        botonAgregarLibro = new javax.swing.JButton();
        botonActualizarLibro = new javax.swing.JButton();
        botonEliminarLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelVentanaLibreria.setPreferredSize(new java.awt.Dimension(400, 300));

        lblIdLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblIdLibro.setText("ID");

        lblAutorLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblAutorLibro.setText("Autor");

        lblNombreLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreLibro.setText("Libro");

        lblEditorialLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblEditorialLibro.setText("Editorial");

        lblEdicionLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblEdicionLibro.setText("Edición");

        txtIdLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLibroActionPerformed(evt);
            }
        });

        txtAutorLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorLibroActionPerformed(evt);
            }
        });

        botonAgregarLibro.setText("Agregar Libro");
        botonAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarLibroActionPerformed(evt);
            }
        });

        botonActualizarLibro.setText("Actualizar Libro");
        botonActualizarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarLibroActionPerformed(evt);
            }
        });

        botonEliminarLibro.setText("Eliminar Libro");
        botonEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVentanaLibreriaLayout = new javax.swing.GroupLayout(panelVentanaLibreria);
        panelVentanaLibreria.setLayout(panelVentanaLibreriaLayout);
        panelVentanaLibreriaLayout.setHorizontalGroup(
            panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentanaLibreriaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonAgregarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonActualizarLibro)
                .addGap(12, 12, 12)
                .addComponent(botonEliminarLibro)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentanaLibreriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentanaLibreriaLayout.createSequentialGroup()
                        .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditorialLibro)
                            .addComponent(lblAutorLibro)
                            .addComponent(lblIdLibro))
                        .addGap(52, 52, 52)
                        .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelVentanaLibreriaLayout.createSequentialGroup()
                        .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEdicionLibro)
                            .addComponent(lblNombreLibro))
                        .addGap(56, 56, 56)
                        .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdicionLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95))
        );
        panelVentanaLibreriaLayout.setVerticalGroup(
            panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentanaLibreriaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdLibro)
                    .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAutorLibro))
                .addGap(18, 18, 18)
                .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreLibro))
                .addGap(18, 18, 18)
                .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorialLibro)
                    .addComponent(txtEditorialLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdicionLibro)
                    .addComponent(txtEdicionLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelVentanaLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarLibro)
                    .addComponent(botonActualizarLibro)
                    .addComponent(botonEliminarLibro))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentanaLibreria, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentanaLibreria, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLibroActionPerformed

    private void txtAutorLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorLibroActionPerformed

    private void botonAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarLibroActionPerformed
        Libro libro = new Libro();
        libro.setIdLibro(Integer.parseInt(txtIdLibro.getText()));
        libro.setNombreDelAutor(txtAutorLibro.getText());
        libro.setNombreDelLibro(txtNombreLibro.getText());
        libro.setNombreDeLaEditorial(txtEditorialLibro.getText());
        libro.setEdicion(Integer.parseInt(txtEdicionLibro.getText()));
        libro.setEstado(true);
        ControlDeLibro controlador = new ControlDeLibro();
        controlador.agregarLibro(libro);
        
        
    }//GEN-LAST:event_botonAgregarLibroActionPerformed

    private void botonActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarLibroActionPerformed
        Libro libro = new Libro();
        libro.setIdLibro(Integer.parseInt(txtIdLibro.getText()));
        libro.setNombreDelAutor(txtAutorLibro.getText());
        libro.setNombreDelLibro(txtNombreLibro.getText());
        libro.setNombreDeLaEditorial(txtEditorialLibro.getText());
        libro.setEdicion(Integer.parseInt(txtEdicionLibro.getText()));
        libro.setEstado(true);
        ControlDeLibro controlador = new ControlDeLibro();
        controlador.actualizarLibro(libro);
    }//GEN-LAST:event_botonActualizarLibroActionPerformed

    private void botonEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarLibroActionPerformed
        Libro libro = new Libro();
        libro.setIdLibro(Integer.parseInt(txtIdLibro.getText()));
        ControlDeLibro controlador = new ControlDeLibro();
        controlador.eliminarLibro(libro);
    }//GEN-LAST:event_botonEliminarLibroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarLibro;
    private javax.swing.JButton botonAgregarLibro;
    private javax.swing.JButton botonEliminarLibro;
    private javax.swing.JLabel lblAutorLibro;
    private javax.swing.JLabel lblEdicionLibro;
    private javax.swing.JLabel lblEditorialLibro;
    private javax.swing.JLabel lblIdLibro;
    private javax.swing.JLabel lblNombreLibro;
    private javax.swing.JPanel panelVentanaLibreria;
    private javax.swing.JTextField txtAutorLibro;
    private javax.swing.JTextField txtEdicionLibro;
    private javax.swing.JTextField txtEditorialLibro;
    private javax.swing.JTextField txtIdLibro;
    private javax.swing.JTextField txtNombreLibro;
    // End of variables declaration//GEN-END:variables
}
